### ISSUE TITLE
WSLでの開発環境構築

### ISSUE THREAD

**Issue by yu2ta7ka** [tomoyuki-nakabayashi/interface202305-c3-std-rust#3]
WSL環境で、改めて環境構築を実施しました。
ターゲットへの書き込みまでは完了しているようなのですが、「waiting for download」と出力されて停止しております。下記ログより何か気になる点ありませんでしょうか？
![image](https://user-images.githubusercontent.com/44434953/229337392-42c44f1a-22f7-4246-b3af-b7ee155182c7.png)

0x4004c51a - chip726_phyrom_version_num
    at ??:??
となっているところが気になるのですが、対応方針がわかっておりません。
連日お手数をおかけして申し訳ございません。

**Comment by yu2ta7ka** [comment]
FAQに記載いただいている内容でした、失礼しました。

**Comment by tomoyuki-nakabayashi** [comment]
無事、WSL で環境構築できたようでよかったです！
