### ISSUE TITLE
WSLでの環境構築　No.2

### ISSUE THREAD

**Issue by yu2ta7ka** [tomoyuki-nakabayashi/interface202305-c3-std-rust#4]
先日一度Hello, Worldができたのですが、再度「waiting for download」が出てしまうようになり、相談をさせてください。

M5Stamp C3U Mate のボタンを押しながら USB ケーブルを本体に接続して、書き込み(cargo espflash --release --monitor)を実行すると、「waiting for download」となります。issue #3 の状態です。

M5Stamp C3U Mate のボタンを押さずに USB ケーブルを本体に接続して、書き込み(cargo espflash --release --monitor)を実行すると、Matched SerialPortType::Unknownで停止します。5分ほど待っても特に処理が進みません。
![image](https://user-images.githubusercontent.com/44434953/230696495-b9f56609-9156-470b-91c8-a76041c54acf.png)

何か対応方針ありませんでしょうか？
お手数をおかけします。

**Comment by yu2ta7ka** [comment]
https://jl1nie.wordpress.com/2023/04/08/rust%e3%81%a7l%e3%83%81%e3%82%ab%e3%81%97%e3%81%a6%e3%81%bf%e3%81%9f/
こちらの記事を参照して解決しました。
「USBデバイスのWSLへの接続」の項目で私の環境では不備がありました。

**Comment by tomoyuki-nakabayashi** [comment]
反応遅れました。無事解決できたようで良かったです！

**Comment by yu2ta7ka** [comment]
ご確認ありがとうございます。
二週間かけてついにスタート地点に立てた感じです。これから本編楽しませていただきます！
